### ISSUE TITLE
Slideshow doesn't work

### ISSUE THREAD

**Issue by Tresillo2017** [MakD/zombie-release#13]
After following the guide on how to setup the slideshow I'm getting an error everytime it tries to load
```less
Uncaught (in promise) TypeError: slides[shuffledIndexes[index]] is undefined
    showSlide https://jellyfin.example.com/web/avatars/slideshow.html:216
    initializeSlideshow https://jellyfin.example.com/web/avatars/slideshow.html:224
    fetchMoviesFromServer https://jellyfin.example.com/web/avatars/slideshow.html:319
```

**Comment by MakD** [comment]
Can you try the latest slideshow.html uploaded? Made couple of changes. Also are you on windows or Linux

**Comment by MakD** [comment]
Can you try this for docker

https://github.com/BobHasNoSoul/jellyfin-mods/blob/main/help.md#docker-linux-and-jellyfin-official-image

**Comment by Tresillo2017** [comment]
> Can you try this for docker
> 
> https://github.com/BobHasNoSoul/jellyfin-mods/blob/main/help.md#docker-linux-and-jellyfin-official-image

Tried it but didn't work, I will share my docker compose file
```yaml
---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=https://jellyfin.example.com #optional
      - NVIDIA_VISIBLE_DEVICES=all
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${PWD}/config:/config
      - /mnt/jellyfin/tvseries:/data/tvshows
      - /mnt/jellyfin/movies:/data/movies
      - /mnt/jellyfin/music:/data/music
      - /mnt/jellyfin/intros:/data/intros
      - /mnt/jellyfin/books:/data/books
      - ${PWD}/custom-html-chunk.js:/usr/share/jellyfin/web/home-html.8ce38bc7d6dc073656d4.chunk.js
      - ${PWD}/avatars:/usr/share/jellyfin/web/avatars
      - /dev/vscm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /opt/vc/lib:/opt/vc/lib
      - /dev/dri/:/dev/dri/
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
```
